### ISSUE TITLE
Plugin can't locate the dart-sass executable when running as part of multi-stage docker build

### ISSUE THREAD

**Issue by RobMaskell** [EtienneMiret/sass-gradle-plugin#13]
This used to work both in the IDE and also in the multi-stage docker build, but I've evergreened a few versions and now I get this error in the docker build, but it still works ok in the IDE (vscode)
```
Caused by: net.rubygrapefruit.platform.NativeException: Could not start '/application/.gradle/sass/dart-sass/sass'
	at net.rubygrapefruit.platform.internal.DefaultProcessLauncher.start(DefaultProcessLauncher.java:27)
	at net.rubygrapefruit.platform.internal.WrapperProcessLauncher.start(WrapperProcessLauncher.java:36)
	at org.gradle.process.internal.ExecHandleRunner.startProcess(ExecHandleRunner.java:98)
	at org.gradle.process.internal.ExecHandleRunner.run(ExecHandleRunner.java:71)
	... 4 more
Caused by: java.io.IOException: Cannot run program "/application/.gradle/sass/dart-sass/sass" (in directory "/application"): error=2, No such file or directory
	at net.rubygrapefruit.platform.internal.DefaultProcessLauncher.start(DefaultProcessLauncher.java:25)
	... 7 more
Caused by: java.io.IOException: error=2, No such file or directory
	... 8 more
```

Gradle version: 7.2
Java version: 16

```
plugins {
	id 'io.miret.etienne.sass' version '1.1.1'
}
sass {
	version = '1.41.1'
	baseUrl = 'https://github.com/sass/dart-sass/releases/download'
}
```
Same issue on 1.1.2

Looking in the docker build, the file does seem to exist at `/application/.gradle/sass/dart-sass/sass`

**Comment by RobMaskell** [comment]
I created a simple demo (just to check I hadn't made any obviously silly mistakes)

run `docker build --force-rm .` in the project root directory and you should see the stacktrace and proof that the `sass` file is there

[demo.zip](https://github.com/EtienneMiret/sass-gradle-plugin/files/7190678/demo.zip)

**Comment by RobMaskell** [comment]
I created a simple demo (just to check I hadn't made any obviously silly mistakes)

run `docker build --force-rm .` in the project root directory and you should see the stacktrace and proof that the sass file is there
[demo.zip](https://github.com/EtienneMiret/sass-gradle-plugin/files/7190691/demo.zip)

**Comment by EtienneMiret** [comment]
Hi!

Thank for reporting this issue. It is due to the fact that `dart-sass` won’t run on Alpine Linux (see [[1]]). You can fix it by using another distribution with the appropriate [adoptopenjdk/openjdk16] tag. I just tested the `:debian` tag and it worked fine.

Regards,

[1]: https://github.com/sass/dart-sass/issues/617#issuecomment-470936879
[adoptopenjdk/openjdk16]: https://hub.docker.com/r/adoptopenjdk/openjdk16
