### ISSUE TITLE
Gradle 8.0-rc-1: Unable to expand TAR '....tar.gz'

### ISSUE THREAD

**Issue by dubinsky** [EtienneMiret/sass-gradle-plugin#28]
I am seeing a failure with Gradle 8.0-rc-1:
```
$ ./gradlew installSass --stacktrace
...
> Task installSass FAILED
...
> Unable to expand TAR '.../.gradle/sass/archive/dart-sass-1.57.1-linux-x64.tar.gz'
    The tar might be corrupted or it is compressed in an unexpected way.
    By default the tar tree tries to guess the compression based on the file extension.
    If you need to specify the compression explicitly please refer to the DSL reference.
...
Caused by: java.io.IOException: Not a TAR archive
        at org.gradle.api.internal.file.archive.TarFileTree.checkFormat(TarFileTree.java:178)
        at org.gradle.api.internal.file.archive.TarFileTree.visitImpl(TarFileTree.java:103)
        at org.gradle.api.internal.file.archive.TarFileTree.lambda$visit$0(TarFileTree.java:88)
        ... 63 more
```

**Comment by EtienneMiret** [comment]
I can confirm this. However, everything is fine with Gradle 8.0 and 8.1.1. I guess this was a bug in Gradle 8.0-rc-1 itself, but I won’t spend time investigate.
